let nationalParks = {
	'Denali National Park': 'Alaska',
	'Gates of the Arctic National Park': 'Alaska',
	'Glacier Bay National Park': 'Alaska',
	'Katmai National Park': 'Alaska',
	'Kenai Fjords National Park': 'Alaska',
	'Kobuk Valley National Park': 'Alaska',
	'Lake Clark National Park': 'Alaska',
	'Wrangell-St. Elias National Park': 'Alaska',
	'National Park of American Samoa': 'American Samoa',
	'Grand Canyon National Park': 'Arizona',
	'Petrified Forest National Park': 'Arizona',
	'Saguaro National Park': 'Arizona',
	'Hot Springs National Park': 'Arkansas',
	'Channel Islands National Park': 'California',
	'Death Valley National Park': 'California, Nevada',
	'Joshua Tree National Park': 'California',
	'Kings Canyon National Park': 'California',
	'Lassen Volcanic National Park': 'California',
	'Pinnacles National Park': 'California',
	'Redwood National Park': 'California',
	'Sequoia National Park': 'California',
	'Yosemite National Park': 'California',
	'Black Canyon of the Gunnison National Park': 'Colorado',
	'Great Sand Dunes National Park': 'Colorado',
	'Mesa Verde National Park': 'Colorado',
	'Rocky Mountain National Park': 'Colorado',
	'Biscayne National Park': 'Florida',
	'Dry Tortugas National Park': 'Florida',
	'Everglades National Park': 'Florida',
	'Haleakala National Park': 'Hawaii',
	'Hawai’i Volcanoes National Park': 'Hawaii',
	'Yellowstone National Park': 'Idaho, Montana, Wyoming',
	'Mammoth Cave National Park': 'Kentucky',
	'Indiana Dunes National Park': 'Indiana',
	'Acadia National Park': 'Maine',
	'Isle Royale National Park': 'Michigan',
	'Voyageurs National Park': 'Minnesota',
	'Gateway Arch National Park': 'Missouri',
	'Glacier National Park': 'Montana',
	'Great Basin National Park': 'Nevada',
	'Carlsbad Caverns National Park': 'New Mexico',
	'White Sands National Park': 'New Mexico',
	'Theodore Roosevelt National Park': 'North Dakota',
	'Great Smoky Mountains National Park': 'North Carolina, Tennessee',
	'Cuyahoga Valley National Park': 'Ohio',
	'Crater Lake National Park': 'Oregon',
	'Congaree National Park': 'South Carolina',
	'Badlands National Park': 'South Dakota',
	'Wind Cave National Park': 'South Dakota',
	'Big Bend National Park': 'Texas',
	'Guadalupe Mountains National Park': 'Texas',
	'Arches National Park': 'Utah',
	'Bryce Canyon National Park': 'Utah',
	'Canyonlands National Park': 'Utah',
	'Capitol Reef National Park': 'Utah',
	'Zion National Park': 'Utah',
	'Virgin Islands National Park': 'Virgin Islands',
	'Shenandoah National Park': 'Virginia',
	'Mount Rainier National Park': 'Washington',
	'North Cascades National Park': 'Washington',
	'Olympic National Park': 'Washington',
	'New River Gorge National Park': 'West Virginia',
	'Grand Teton National Park': 'Wyoming',
};
